# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  vars_prompt:
    - name: partition
      prompt: "Enter a partition name"
      default: "Common"

  tasks:
    - name: Print out your input
      debug:
        msg: "You provided the {{ partition }} partition for the 'partition' prompt"
